const images = {
  celebrate: require('./celebrate.png'),
  arrowBack: require('./back.png'),
  eye: require('./eye.png'),
  eyeEnable: require('./eyeEnable.png'),
  facebook: require('./facebook.png'),
  google: require('./google.png'),
  apple: require('./apple-logo.png'),
  checkBoxFilled: require('./checkboxfilled.png'),
  checkBoxEmpty: require('./emptyCheckBox.png'),
  room: require('./room.png'),
  splashBg: require('./splashBg.png'),
  logowithTagline: require('./logowithTagline.png'),
  logowithWOT: require('./logoWOT.png'),
  onboarding1: require('./slide1.png'),
  onboarding2: require('./onboarding2.gif'),
  onboarding3: require('./onboarding3.gif'),
  socialSignUp: require('./socialSignUp.gif'),
  email: require('./email.png'),
  startJourney: require('./startJourney.png'),
  singleRoom: require('./signleRoom.png'),
  sharedRoom: require('./sharedRoom.png'),
  house: require('./house.png'),
  building: require('./building.png'),
  forest: require('./forest.png'),
  search: require('./search.png'),
  mapPin: require('./mapPin.png'),
  locationIcon: require('./locationIcon.png'),
  calender: require('./calender.png'),
  outdoor: require('./outdoor.png'),
  biking: require('./biking.png'),
  museums: require('./museums.png'),
  food: require('./food.png'),
  culturalCenters: require('./culturalCenters.png'),
  bars: require('./bars.png'),
  addPropertyIcon: require('./addPropertyIcon.png'),
  cardImage: require('./cardImage.png'),
  calenderOrange: require('./calenderOrange.png'),
  roomIcon: require('./roomIcon.png'),
  personIcon: require('./personIcon.png'),
  location: require('./location.png'),
  smallCardImage: require('./smallCardImage.png'),
  userImage: require('./userImage.png'),
  cross: require('./cross.png'),
  camera: require('./camera.png'),
  gallery: require('./gallery.png'),
  backArrowIcon: require('./backArrowIcon.png'),
  glob: require('./homw.png'),
  exchange: require('./bookmark.png'),
  message: require('./messenger.png'),
  profile: require('./profile.png'),
  notification: require('./notification.png'),
  userProfile: require('./userProfile.jpeg'),
  exchange_calender: require('./calendar_exchange.png'),
  date: require('./date.png'),
  map_location: require('./map_location.png'),
  rooms: require('./rooms.png'),
  profileBg: require('./profileBg.png'),
  settings: require('./settings.png'),
  rightArrow: require('./rightArrow.png'),
  lock: require('./lock.png'),
  help: require('./help.png'),
  document: require('./document.png'),
  cameraIcon: require('./cameraIcon.png'),
  cancel: require('./cancel.png'),
  connectionSentIcon: require('./connectionSentIcon.gif'),
  avatar: require('./avatar.gif'),
  sendIcon: require('./send.png'),
  moreOptions: require('./moreOptions.png'),
  noMessages: require('./noMessages.png'),
  radioSelected: require('./radioSelected.png'),
  radioUnSelected: require('./radioUnSelected.png'),
  logout: require('./logout.png'),
  video1: require('./video1.png'),
  video2: require('./video2.png'),
  galleryImage1: require('./galleryImage1.png'),
  galleryImage2: require('./galleryImage2.png'),
  galleryImage3: require('./galleryImage3.png'),
  playIcon: require('./playButton.png'),
  play: require('./play.png'),
  passwordUpdated: require('./passwordUpdated.gif'),
  appLogo: require('./applogo.png'),
  splash: require('./splash_gif.gif'),
  imagePlaceHolder: require('./productDetailsImag.png'),
  africa:require("./africa.png"),
  antarctica:require("./Antarctica.png"),
  asia:require("./asia.png"),
  northAmerica:require("./northAmerica.png"),
  southAmerica:require("./southAmerica.png"),
  chat:require("./chat.png"),
  edit:require("./edit.png"),
  secure:require("./secure.png"),
  user:require("./user.png"),
  attachment:require("./attachment.png"),
  arrow_down:require("./arrow_down.png"),
  success:require("./success.png"),
  three_dots:require("./3dotscircle.png"),
  start_rating:require("./star_rating.png"),
  three_menu:require("./three_menu.png"),
  // AG GROUP //

  gold:require("./gold.png"),
  gold_plus:require("./gold_plus.png"),
  diamond:require("./diamond.png"),
  faisal_bank:require("./faisal_bank.png"),
  alflah_bank:require("./alfla_bank.png"),
  menu:require("./more.png"),
  prayer:require("./prayer.png"),
  qrCode:require("./qrCode.png"),
  song:require("./song.png"),
  backButton:require("./back.png"),
  share:require("./share.png"),
  sun:require("./sun.png"),
  addPrayer:require("./addPrayer.png"),
  setTime:require("./setTime.png"),
  qr_code_placeholder:require("./qrcode_placeholder.png"),
  allied:require("./allied.png"),
  notificationBg:require("./notificationBg.png"),
  tick:require("./tick.png"),
  newArticle:require("./newArticle.png"),
  pending:require("./pending.png"),
  productImage:require("./photo.png"),
  price:require("./price.png"),
  condition:require("./condition.png"),
  handShake:require("./hand_shake.png"),
  article:require("./article.png"),
  scooter:require("./scooter.png"),
  info:require("./info.png"),
  priceChild:require("./priceChild.png"),
  time:require("./time.png"),
  booster:require("./booster.png"),
  add:require("./add.png"),
  chatFilter:require("./chatFilter.png"),
  delete:require("./delete.png"),
  pause:require("./pause.png"),
  edit2:require("./edit2.png"),



};

export default images;
