const Reacts = require('react-native');
const {Dimensions, Platform} = Reacts;
const deviceHeight = Dimensions.get('window').height;
const deviceWidth = Dimensions.get('window').width;

export default {
  mb40: {
    marginBottom: 40,
    height: 40,
  },
  pt5: {
    paddingTop: 5,
  },
  pt10: {
    paddingTop: 10,
  },
  pt15: {
    paddingTop: 15,
  },
  pt20: {
    paddingTop: 20,
  },
  pt30: {
    paddingTop: 30,
  },
  ma0: {
    margin: 0,
  },
  mb5: {
    marginBottom: 5,
  },
  mb10: {
    marginBottom: 10,
  },
  mb15: {
    marginBottom: 15,
  },
  mb20: {
    marginBottom: 20,
  },
  mb25: {
    marginBottom: 25,
  },
  mb30: {
    marginBottom: 30,
  },
  mb80: {
    marginBottom: 80,
  },

  mt5: {
    marginTop: 5,
  },
  mt10: {
    marginTop: 10,
  },
  mt15: {
    marginTop: 15,
  },
  mt20: {
    marginTop: 20,
  },
  mt30: {
    marginTop: 30,
  },

  ml5: {
    marginLeft: 5,
  },
  ml10: {
    marginLeft: 10,
  },
  ml15: {
    marginLeft: 15,
  },
  ml20: {
    marginLeft: 20,
  },
  ml30: {
    marginLeft: 30,
  },

  mr5: {
    marginRight: 5,
  },
  m10: {
    margin: 10,
  },
  mr10: {
    marginRight: 10,
  },
  mr15: {
    marginRight: 15,
  },
  mr20: {
    marginRight: 20,
  },
  mr30: {
    marginRight: 30,
  },
  h250: {
    height: 200,
  },
  h200: {
    height: 200,
  },
  h150: {
    height: 150,
  },
  h100: {
    height: 100,
  },
  h50: {
    height: 50,
  },
  h30: {
    height: 30,
  },
  container: {
    backgroundColor: '#ffffff',
    OverflowEvent: 'auto',
    flex: 1,
    fontFamily: 'Futura',
  },
  textleft: {
    textAlign: 'left',
  },
  textright: {
    textAlign: 'right',
  },
  textcenter: {
    textAlign: 'center',
  },
  totalWrap: {
    marginTop: 20,
    marginBottom: 5,
    backgroundColor: '#F5F8FF',
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  agreelabelsignup: {
    marginBottom: -2,
    marginLeft: 5,
    fontSize: 12,
    color: '#44852F',
    fontWeight: '300',
  },
  amountText: {
    fontSize: 16,
    color: '#595B71',
    textAlign: 'center',
  },

  // scrollView:{
  //   paddingRight: 19,
  //   paddingTop: 40,
  //   paddingBottom: 10,
  //   paddingLeft: 19,
  // },

  homescrollView: {
    paddingRight: 19,
    paddingTop: 20,
    paddingBottom: 0,
    paddingLeft: 19,
    overflow: 'scroll',
  },
  scrollView: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingRight: 33,
    paddingLeft: 33,
  },
  scrollView_nopadding: {
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: 10,
    paddingLeft: 10,
  },
  detail_View: {
    paddingTop: 18,
    paddingBottom: 18,
    paddingRight: 10,
    paddingLeft: 10,
  },
  headercontainer: {
    width: deviceWidth,
    backgroundColor: '#44852F',
    height: 250,
    marginTop: -30,
    paddingLeft: 35,
    width: deviceWidth,
    alignItems: 'center',
    textAlign: 'center',
  },
  headershort: {
    height: 200,
  },
  headerback: {
    height: 40,
    width: 40,
  },
  headertop: {
    width: deviceWidth,
    height: 60,
    textAlign: 'left',
    alignItems: 'center',
    alignSelf: 'center',
  },
  headerleft: {
    width: deviceWidth / 1.2,
    flex: 1,
    textAlign: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  headerright: {
    width: deviceWidth - deviceWidth / 1.2,
    flex: 2,
    alignItems: 'center',
    alignSelf: 'center',
  },
  headingText: {
    width: deviceWidth / 1.6,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '400',
    color: '#ffffff',
  },
  titleloginheading: {
    color: '#44852F',
    fontSize: 20,
    lineHeight: 27,
    fontWeight: '600',
  },
  titleheading: {
    color: '#44852F',
    fontSize: 20,
    lineHeight: 27,
    fontWeight: '600',
    marginBottom: 30,
  },
  titlemainheading: {
    color: '#44852F',
    fontSize: 20,
    textTransform: 'uppercase',
    lineHeight: 20,
    fontWeight: '600',
    marginBottom: 20,
  },
  fourcolheading: {
    color: '#44852F',
    fontSize: 20,
    textTransform: 'uppercase',
    lineHeight: 27,
    fontWeight: '600',
    //marginBottom:30,
  },
  titlemainhead: {
    color: '#5A5A5A',
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    marginBottom: 15,
  },
  texttitle: {
    /*color: "#B7B7B7",
    fontSize: 15,
    lineHeight: 20,
    marginBottom: 16*/
    color: '#B7B7B7',
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    marginBottom: 15,
  },
  textsubtitle: {
    color: '#B7B7B7',
    fontSize: 15,
    lineHeight: 20,
    marginBottom: 15,
    fontWeight: '700',
  },
  SectionStyle: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    height: 40,
    marginLeft: 0,
    borderRadius: 5,
    position: 'relative',
    // borderBottomColor: '#B7B7B7',
    // borderBottomWidth: 2,
    color: '#B7B7B7',
  },
  ImageStyle: {
    padding: 0,
    marginTop: 0,
    marginLeft: 0,
    resizeMode: 'stretch',
    alignItems: 'center',
    position: 'absolute',
    left: 0,
    top: 0,
  },
  icon_user: {
    // height: 22,
    // width: 22,
  },
  icon_phone: {
    // height: 20,
    // width: 20,
    marginTop: 5,
  },
  icon_email: {
    // height: 22,
    // width: 22,
  },

  inputicon: {
    flex: 2,
    resizeMode: 'cover',
    justifyContent: 'flex-start',
  },
  nameinput: {
    //height: 33,
    flex: 1,
    // padding: 10,
    marginLeft: -10,
    //marginBottom:40,
    borderBottomColor: '#B7B7B7',
    borderBottomWidth: 2,
    color: '#B7B7B7',
    paddingLeft: 30,
    fontSize: 14,
    lineHeight: 30,
  },
  phoneinput: {
    //height: 33,
    flex: 1,
    // padding: 10,
    marginLeft: -10,
    //marginBottom:40,
    borderBottomColor: '#B7B7B7',
    borderBottomWidth: 2,
    color: '#B7B7B7',
    fontSize: 14,
    lineHeight: 30,
    paddingBottom: 10,
    paddingLeft: 35,
    //textAlignVertical: 'top',
  },
  emailinput: {
    //height: 33,
    flex: 1,
    // padding: 10,
    marginLeft: -10,
    //marginBottom:40,
    borderBottomColor: '#B7B7B7',
    borderBottomWidth: 2,
    color: '#B7B7B7',
    paddingLeft: 30,
    fontSize: 14,
    lineHeight: 30,
  },
  otpinput: {
    width: deviceWidth / 1.8,
    padding: 0,
    marginLeft: 0,
    marginTop: 20,
    borderBottomColor: '#B7B7B7',
    borderBottomWidth: 2,
    color: '#B7B7B7',
    paddingLeft: 25,
    fontSize: 14,
  },
  setting_input: {
    width: deviceWidth / 1.5,
    padding: 0,
    marginLeft: 0,
    marginTop: 20,
    borderBottomColor: '#B7B7B7',
    borderBottomWidth: 2,
    color: '#B7B7B7',
    paddingLeft: 25,
    fontSize: 14,
  },
  maininput: {
    flex: 1,
    padding: 10,
    marginLeft: 0,
    // borderColor: '#B7B7B7',
    // borderWidth: 2,
    // color: '#B7B7B7'
  },
  imageContainer: {
    flex: 1,
    width: null,
    height: null,
  },
  logoContainer: {
    flex: 1,
    marginTop: deviceHeight / 8,
    marginBottom: 30,
  },
  errorInput: {
    flex: 1,
    marginTop: -24,
    marginLeft: 8,
    marginBottom: 24,
    color: '#ff0000',
    borderWidth: 0,
    outline: 'none',
    shadowColor: '#000',
    shadowOffset: {
      width: 6,
      height: 3,
    },
    shadowOpacity: 0.16,
  },
  forminput: {
    marginLeft: 0,
  },
  hide: {
    display: 'none',
  },
  progressstep: {
    display: 'none',
  },
  input_text: {
    paddingLeft: 30,
    marginTop: 10,
    height: 41,
    fontSize: 14,
    /* marginBottom: -1,  */
    borderBottomWidth: 1,
    borderBottomColor: '#B7B7B7',
    color: '#242729',
  },
  input_text_1: {
    paddingLeft: 40,
    marginTop: 15,
    height: 41,
    fontSize: 16,
    /* marginBottom: -1,  */
    borderBottomWidth: 1,
    borderBottomColor: '#B7B7B7',
    color: '#242729',
  },

  input_text_half: {
    paddingLeft: 10,
    marginTop: 14,
    height: 40,
    fontSize: 16,
    lineHeight: 16,
    //marginBottom: -1,
    borderBottomWidth: 1,
    borderBottomColor: '#B7B7B7',
    color: '#242729',
    marginTop: 0,
  },
  input_texticon: {
    paddingLeft: 45,
    /* textTransform:"uppercase", */
    marginBottom: 0,
  },
  inputtext: {
    paddingLeft: 10,
    marginTop: 14,
    height: 41,
    fontSize: 14,
    lineHeight: 16,
    marginBottom: -1,
    borderBottomWidth: 1,
    borderBottomColor: '#B7B7B7',
    color: '#242729',
  },

  input_text_option: {
    paddingLeft: 13.5,
    marginTop: 0,
    height: 42,
    fontSize: 16,
    lineHeight: 12,
    borderWidth: 1,
    borderColor: '#B7B7B7',
    borderRadius: 5,
    //marginBottom:-4,
    marginBottom: 0,
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: '#B7B7B7',
    backgroundColor: '#ffffff',
    color: '#242729',
  },
  input_img: {
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    position: 'absolute',
    top: 20,
    left: 10,
  },
  input_img_1: {
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    position: 'absolute',
    top: 24,
    left: 10,
  },

  input_img_icon: {
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    position: 'absolute',
    top: 20,
    left: 6,
  },
  input_img_address: {
    width: 22,
    height: 22,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    position: 'absolute',
    top: 18,
    left: 6,
  },
  input_img_web: {
    width: 20,
    height: 10,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    position: 'absolute',
    top: 25,
    left: 10,
  },
  maptitle: {
    color: '#5A5A5A',
    fontSize: 12,
    lineHeight: 22,
    marginBottom: 9,
  },

  maplink: {
    color: '#0039D5',
    fontSize: 12,
    lineHeight: 22,
    marginBottom: 10,
  },
  map_img: {
    // width: 269,
    height: 204,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    marginBottom: 8,
  },
  destitle: {
    color: '#B7B7B7',
    textTransform: 'uppercase',
    fontSize: 14,
    lineHeight: 16,
    marginBottom: 17,
  },

  addoption: {
    color: '#ffffff',
    lineHeight: 50,
    fontSize: 18,
    marginBottom: 0,
  },
  close_icon: {
    color: '#ffffff',
    lineHeight: 50,
    fontSize: 14,
    margin: 0,
    alignItems: 'center',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
  },
  close_icon_text: {
    color: '#ffffff',
    width: 20,
    height: 20,
    alignItems: 'center',
    textAlign: 'center',
  },
  describetitle: {
    color: '#B7B7B7',
    fontSize: 14,
    lineHeight: 16,
    marginBottom: 17,
    position: 'absolute',
    top: -9,
    left: 10,
    backgroundColor: '#ffffff',
    zIndex: 1,
  },

  uploadtitle: {
    color: '#5A5A5A',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 16,
    lineHeight: 16,
    marginBottom: 11,
  },
  footer: {
    position: 'absolute',
    flex: 0.1,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    height: 60,
    width: deviceWidth,
    shadowColor: '#000',
    shadowOffset: {
      width: 1,
      height: 6,
    },
    shadowOpacity: 0.16,
    shadowRadius: 3.84,
    elevation: 5,
    alignItems: 'center',
    textAlign: 'center',
  },
  imageButtons: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    color: '#595B71',
  },
  btnupload: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoButtons: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    color: '#595B71',
  },
  bottomButtons: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    color: '#595B71',
  },
  footer_text: {
    fontWeight: 'normal',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#595B71',
    fontSize: 9,
  },
  footer_img: {
    // width:30,
    // height:30,
    width: 24,
    height: 24,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginBottom: 0,
  },
  textStyle: {
    alignSelf: 'center',
    color: '#595B71',
  },
  textStyleclose: {
    alignSelf: 'center',
    color: '#5D5D5D',
    fontWeight: 'bold',
  },
  logo: {
    position: 'absolute',
    right: Platform.OS === 'android' ? 10 : 10,
    top: Platform.OS === 'android' ? 5 : 5,
    width: 40,
    height: 40,
  },
  mb: {
    marginBottom: 15,
  },
  loginText: {
    color: '#ffffff',
    fontSize: 16,
  },
  mainBtn: {
    width: '98%',
    borderRadius: 10,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
    backgroundColor: '#228B22',
  },
  loginBtn: {
    width: '98%',
    borderRadius: 10,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
    backgroundColor: '#228B22',
  },
  term_button: {
    height: 30,
    marginBottom: 30,
    marginLeft: 20,
    color: '#B7B7B7',
  },
  text: {
    color: '#D8D8D8',
    bottom: 6,
    marginTop: 5,
  },
  agreelabel: {
    marginTop: 15,
    fontSize: 16,
    color: '#44852F',
    fontWeight: '300',
  },
  viewlogincomponent: {
    flex: 1,
    paddingBottom: 20,
  
    backgroundColor: 'transparent',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,bottom:100,
  },
  viewcomponent: {
    flex: 1,
    paddingTop: 20,
    paddingBottom: 20,
    paddingRight: 0,
    paddingLeft: 0,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    marginTop: -40,
  },
  viewdetail: {
    flex: 1,
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: 0,
    paddingLeft: 0,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    marginTop: 40,
  },

  viewdetail_gray: {
    flex: 1,
    paddingTop: 30,
    paddingBottom: 20,
    paddingRight: 0,
    paddingLeft: 0,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    marginTop: -40,
    /* flex: 1, 
    paddingTop: 0,  
    paddingBottom: 0, 
    paddingRight: 0, 
    paddingLeft: 0,  
    backgroundColor: "#F7F5F5",
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    marginTop:0 */
  },
  l_r_space: {
    paddingRight: 33,
    paddingLeft: 33,
  },
  homeviewcomponent: {
    flex: 1,
    paddingTop: 0,
    paddingBottom: 40,
    paddingRight: 0,
    paddingLeft: 0,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    marginTop: -40,
    position: 'relative',
    overflow: 'hidden',
  },
  viewhomecomponent: {
    flex: 1,
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: 0,
    paddingLeft: 0,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    marginTop: -40,
    position: 'relative',
    overflow: 'hidden',
  },
  searchlist: {
    position: 'absolute',
    top: -25,
    width: deviceWidth / 1.32,
    left: 45,
  },
  searchbar: {
    backgroundColor: '#F2F2F2',
    borderWidth: 0,
    borderRadius: 100,
    padding: 0,
    // height: 40,
    paddingTop: 11,
    paddingBottom: 13,
    paddingLeft: 31,
    paddingRight: 15,
    overflow: 'hidden',
    color: '#5A5A5A',
    shadowColor: '#000000',
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '500',
    shadowOffset: {
      width: 6,
      height: 3,
    },
    shadowOpacity: 0.16,
  },

  searchbarinn: {
    // backgroundColor:"#ff0000"
  },
  modalopt: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    width: deviceWidth / 1.15,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    height: 200,
  },
  modalViewerVideos: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    marginLeft: 5,
    marginRight: 5,
    width: deviceWidth / 1.05,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    height: deviceHeight - 40,
  },
  modalViewer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    width: deviceWidth / 1.05,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    height: deviceHeight - 40,
  },
  modalViewersetting: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    width: deviceWidth / 1.05,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    height: deviceHeight - 40,
  },
  modalcenteredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
    marginTop: 0,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    width: deviceWidth / 1.15,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000000',
    height: 270,
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalViewsetting: {
    margin: 20,
    width: deviceWidth / 1.15,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000000',
    minheight: 180,
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  settingpopuphead: {
    color: '#44852F',
    fontSize: 14,
    lineHeight: 27,
    fontWeight: '600',
    marginBottom: 0,
  },
  modalViewCategories: {
    margin: 20,
    width: deviceWidth / 1.15,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000000',

    height: 350,
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalMeida: {
    margin: 10,
    width: deviceWidth,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 10,
    alignItems: 'center',
    shadowColor: '#000000',

    height: deviceHeight,
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  business_btn_text: {
    color: '#ffffff',
  },
  fullbutton: {
    // width:"100%",
    borderRadius: 5,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    //marginBottom: 20,
    backgroundColor: '#228B22',
  },
  tagdays: {
    color: '#5A5A5A',
    //height: 20,
    marginTop: 5,
    marginBottom: 5,
    backgroundColor: '#EAEAEA',
    textAlign: 'center',
    padding: 5,
  },
  removefullbutton: {
    // width:"100%",
    borderRadius: 5,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
    backgroundColor: '#228B22',
  },
  removemediavideobutton: {
    borderRadius: 5,
    right: 10,
    top: 5,
    alignSelf: 'center',
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
    backgroundColor: '#FFFFFF',
    zIndex: 222,
  },
  removemediabutton: {
    width: 20,
    borderRadius: 5,
    height: 20,
    right: 10,
    top: 5,
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
    backgroundColor: '#44852f',
    zIndex: 222,
  },
  buttonCloseview: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    position: 'absolute',
    top: 0,
    right: 20,
  },
  buttonCloseviewer: {
    width: 20,
    borderRadius: 10,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  buttonCancelviewer: {
    width: 80,
    borderRadius: 10,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    backgroundColor: '#E7E9EB',
  },
  imageviewer: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  buttondoneviewertext: {
    color: '#FFFFFF',
  },
  listbuttons: {
    width: 100,
    height: 100,
    padding: 10,
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#E7E9EB',
  },

  listvideobuttons: {
    width: deviceWidth - 100,
    height: 100,
    padding: 10,
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#E7E9EB',
  },

  buttondoneviewer: {
    width: 80,
    borderRadius: 10,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    marginLeft: 20,
    marginBottom: 0,
    backgroundColor: '#008000',
  },
  viewer_img: {
    width: deviceWidth / 1.05,
    borderRadius: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    marginTop: 50,
    resizeMode: 'center',
    height: deviceHeight - 90,
  },
  button: {
    width: deviceWidth / 1.5,
    borderRadius: 10,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    backgroundColor: '#228B22',
  },
  buttonhalf: {
    width: deviceWidth / 2.8,
    borderRadius: 10,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
    backgroundColor: '#228B22',
  },
  buttonhalfsetting: {
    width: deviceWidth / 3,
    borderRadius: 10,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',

    backgroundColor: '#228B22',
  },
  buttonhalfsettingclose: {
    width: deviceWidth / 3,
    borderRadius: 10,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ebeef6',
  },
  buttonOpen: {
    backgroundColor: '#228B22',
  },
  buttonClose: {
    backgroundColor: '#228B22',
  },
  pagetitle: {
    color: '#dedede',
    fontSize: 16,
    lineHeight: 27,
    fontWeight: '600',
    marginBottom: 20,
  },
  titleotpheading: {
    color: '#44852F',
    fontSize: 14,
    lineHeight: 27,
    fontWeight: '600',
    marginBottom: 0,
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  menucontainer: {
    overflow: 'visible',
    textAlign: 'center',
    marginBottom: 22,
    borderColor: '#B7B7B7',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  cardcomponent: {
    display: 'flex',
    flexDirection: 'row',
    overflow: 'visible',
    paddingTop: 9,
    paddingLeft: 14,
    paddingBottom: 8,
    paddingRight: 14,
    textAlign: 'right',
    borderColor: 'rgba(183,183,183,0.12)',
    borderWidth: 1,
    overflow: 'visible',
    borderRadius: 20,
    backgroundColor: 'rgba(183,183,183,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardmenucomponent: {
    textAlign: 'right',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  cardmenus: {
    textAlign: 'right',
    width: 20,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  cardtitle: {
    borderRadius: 15,
    width: '90%',
    lineHeight: 53,
    backgroundColor: '#FFFFFF',
    color: '#000',
    fontSize: 12,
    marginRight: 13,
    textAlign: 'center',
    fontWeight: '600',
  },
  menuoptions: {
    borderColor: '#B7B7B7',
    borderWidth: 1,
    borderRadius: 5,
    padding: 0,
    margin: 0,
  },
  menuoption: {
    fontSize: 14,
    padding: 2,
    margin: 0,
  },
  menuTrigger: {
    padding: 5,
  },
  triggerText: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  homecardcomponent: {
    flexDirection: 'row',
  },
  cardcontainer: {
    backgroundColor: '#F2F2F2',
    height: 140,
    paddingTop: 24,
    paddingBottom: 10,
    paddingLeft: 17,
    paddingRight: 15,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    flexDirection: 'column',
    shadowColor: '#000',
    shadowOffset: {
      width: 6,
      height: 3,
    },
    shadowOpacity: 0.16,
    borderRadius: 20,
    marginBottom: 25,
  },
  cardcontaineractive: {
    backgroundColor: '#65A84F',
    //height: 162,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    //flex: 1,
    flexDirection: 'column',
    shadowColor: '#000',
    shadowOffset: {
      width: 6,
      height: 3,
    },
    shadowOpacity: 0.16,
    borderRadius: 20,
    marginBottom: 25,
  },

  cardprocontainer: {
    backgroundColor: '#F2F2F2',
    height: 91,
    paddingTop: 44,
    paddingBottom: 19,
    paddingLeft: 14,
    paddingRight: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    flexDirection: 'column',
    borderRadius: 20,
    marginBottom: 25,
  },

  cardcontainerimg: {
    marginTop: 10,
  },

  promotion_title: {
    fontSize: 12,
    fontWeight: '700',
    color: '#5A5A5A',
    lineHeight: 15,
    marginBottom: 6,
  },
  homebtnwrap: {
    flexDirection: 'row',
  },
  promotion_text: {
    fontSize: 12,
    flexShrink: 1,
    fontWeight: '400',
    color: '#5A5A5A',
    flexShrink: 1,
    lineHeight: 12,
    marginBottom: 18,
  },
  homecardnum: {
    flexDirection: 'row',
    margin: 0,
  },
  homecardnumcontainer: {
    padding: 0,
    margin: 0,
    alignItems: 'stretch',
    justifyContent: 'space-between',
    flex: 1,
    flexDirection: 'column',
    // with: 73
  },
  card_title: {
    borderRadius: 0,
    lineHeight: 27,
    fontSize: 20,
    color: '#9F9F9F',
    textAlign: 'left',
    fontWeight: '400',
    marginTop: 0,
  },
  card_text: {
    borderRadius: 0,
    fontSize: 14,
    lineHeight: 14,
    color: '#5A5A5A',
    textAlign: 'left',
    fontWeight: '400',
    marginTop: 0,
  },

  pro_img: {
    marginTop: -50,
    marginLeft: 0,
    marginRight: 0,
    marginBottom: 10,
    width: 50,
    height: 50,
  },
  tag_img: {
    marginTop: 6,
    marginLeft: 20,
    width: 16,
    height: 16,
  },
  tag_img_eye: {
    marginTop: 3,
    marginLeft: 20,
    width: 20,
    height: 20,
  },
  text_green: {
    color: '#44852F',
  },
  text_blue: {
    color: '#769AFF',
  },
  text_orange: {
    color: '#FC8800',
  },
  text_yellow: {
    color: '#FCCB00',
  },
  text_pink: {
    color: '#FD8A8A',
  },
  text_gray: {
    color: '#9F9F9F',
  },

  cardbtn: {
    // position: 'absolute',
    // bottom: 5,
    marginLeft: 20,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardbtntitle: {
    borderRadius: 15,
    lineHeight: 82,
    color: '#5A5A5A',
    fontSize: 45,
    textAlign: 'center',
    fontWeight: 'bold',
    marginTop: 10,
  },

  datePickerStyle: {
    fontSize: 12,
    // marginLeft:5,
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderLeftWidth: 0,
    textAlign: 'left',
    borderBottomWidth: 1,
    borderBottomColor: '#B7B7B7',
    borderRadius: 0,
    marginLeft: 0,
    marginRight: 0,
    width: '100%',
  },
  cardbtntext: {
    borderRadius: 15,
    width: 118,
    lineHeight: 47,
    backgroundColor: '#FFFFFF',
    color: '#5A5A5A',
    fontSize: 12,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  cardbtnimg: {
    width: 24,
    height: 24,
  },

  homecardcontainer: {
    flexDirection: 'row',
    margin: 0,
    backgroundColor: '#F2F2F2',
    borderRadius: 14,
    paddingTop: 14,
    paddingBottom: 14,
    paddingLeft: 22,
    paddingRight: 22,
  },
  cardbtn_container: {
    marginTop: 8,
    marginLeft: 0,
  },
  cardbtntext_active: {
    borderRadius: 8,
    width: 140,
    lineHeight: 21,
    backgroundColor: '#5DB741',
    color: '#fff',
    fontSize: 12,
    textAlign: 'center',
    fontWeight: 'bold',
  },

  tag_promotion_img: {
    width: 24,
    height: 24,
    position: 'absolute',
    right: 10,
    top: 15,
  },

  reviewbox: {
    borderColor: '#B7B7B7',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderRadius: 5,
    paddingTop: 19,
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 19,
    marginBottom: 16,
  },
  reviewsmalltitle: {
    lineHeight: 14,
    backgroundColor: '#FFFFFF',
    color: '#B7B7B7',
    fontSize: 12,
    textAlign: 'center',
    fontWeight: '400',
    position: 'absolute',
    top: -10,
    left: 25,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 5,
    paddingRight: 5,
  },
  reviewtitlebox: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    marginBottom: 10,
  },
  reviewheading: {
    lineHeight: 14,
    color: '#5A5A5A',
    fontSize: 12,
    textAlign: 'center',
    fontWeight: 'bold',
    marginRight: 21,
  },
  reviewpara: {
    fontSize: 12,
    lineHeight: 15,
    color: '#5A5A5A',
    textAlign: 'left',
    fontWeight: '400',
    marginBottom: 32,
  },
  reviewbtn: {
    backgroundColor: '#44852F',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    textAlign: 'center',
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 50,
    height: 18,
    borderRadius: 30,
    textTransform: 'uppercase',
    fontSize: 12,
    lineHeight: 18,
    color: '#ffffff',
  },

  form_group: {},
  input_form: {
    borderBottomColor: '#B7B7B7',
    borderBottomWidth: 1,
  },

  cardhalfmain: {
    flexDirection: 'row',
  },

  cardhalf: {
    padding: 0,
    paddingLeft: 0,
    paddingRight: 0,
    flex: 1,
    flexDirection: 'column',
    // marginBottom: 25,
    marginLeft: 0,
  },
  cardselect: {
    marginTop: 14,
    // borderBottomColor:"#B7B7B7",
    // borderBottomWidth:1,
  },
  cardselectnomargin: {
    margin: 0,
    marginTop: 0,
  },
  dropdown_picker: {
    color: '#B7B7B7',
    textTransform: 'uppercase',
    borderBottomColor: '#B7B7B7',
    borderBottomWidth: 2,
    // outlineColor: "#B7B7B7",
    // outlineStyle: "solid",
    // outlineWidth: 4,
  },
  hairline: {
    backgroundColor: '#B7B7B7',
    height: 1,
  },
  down_img: {
    width: 12,
    height: 8,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    position: 'absolute',
    top: 18,
    right: 16,
  },
  down_img_sm: {
    width: 12,
    height: 8,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    position: 'absolute',
    top: 18,
    right: 25,
  },
  calender_img: {
    width: 12,
    height: 14,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    position: 'absolute',
    top: 18,
    right: 16,
  },

  select_input: {
    paddingLeft: 0,
    height: 37,
    paddingRight: 20,
    width: 100,
    fontSize: 14,
    lineHeight: 16,
    textTransform: 'uppercase',
  },

  select_input_text: {
    paddingLeft: 0,
    height: 37,
    paddingRight: 20,
    width: 100,
    fontSize: 16,
    lineHeight: 16,
    color: '#B7B7B7',
    textTransform: 'uppercase',

    marginBottom: -1,
    marginTop: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#B7B7B7',
  },
  select_input_border: {
    height: 37,
    paddingRight: 30,
    paddingLeft: 13.5,
    width: 100,
    fontSize: 12,
    lineHeight: 14,
    borderWidth: 1,
    borderColor: '#B7B7B7',
    borderRadius: 5,
    marginBottom: -1,
    outline: 'none',
    shadowColor: '#000',
    shadowOffset: {
      width: 6,
      height: 3,
    },
  },
  /*select_input_line:{
    height: 37, 
    paddingRight:5, 
   // width:100,
    fontSize:12,
    lineHeight: 27,
    color:"#B7B7B7",
    paddingTop:0, 
    paddingLeft:0,
    paddingBottom:5, 
    borderWidth: 2,
    borderColor:'#B7B7B7',
    borderRadius: 0,
    marginBottom: -1,
    borderTop: 0,
    borderRight: 0,
    borderLeft: 0,
    textTransform:"uppercase"
  },*/
  select_input_bottomline: {
    // height: 37,
    height: 47,
    fontSize: 14,
    lineHeight: 27,
    color: '#242729',
    borderColor: '#86939e',
    borderBottomWidth: 1,
    borderBottomColor: '#B7B7B7',
    textTransform: 'uppercase',
    marginBottom: 10,
    paddingBottom: 25,
  },
  textareainput: {
    borderWidth: 1,
    borderColor: '#B7B7B7',
    borderRadius: 5,
    paddingTop: 11,
    paddingBottom: 12,
    paddingLeft: 12,
    paddingRight: 11,
    overflow: 'hidden',
    color: '#242729',
    fontSize: 16,
    lineHeight: 14,
    fontWeight: '500',
    height: 137,
    textAlignVertical: 'top',
    marginBottom: 2,
    // marginBottom: -1,
  },
  current_loc_img: {
    width: 9,
    height: 9,
    marginRight: 7,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    // position: "absolute",
    // top: 18,
    // right: 16,
  },
  cardlistselect: {},
  cardlisttext: {
    borderRadius: 5,
    paddingLeft: 13,
    paddingRight: 13,
    backgroundColor: 'rgba(183, 183, 183, 0.6)',
    marginBottom: 16,
    position: 'relative',
  },
  cardlisttextinn: {
    fontSize: 16,
    lineHeight: 32,
    color: '#666666',
    borderRadius: 5,
    paddingLeft: 13,
    paddingRight: 13,
    position: 'relative',
  },
  circle_close_img: {
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    position: 'absolute',
    top: 9,
    right: 13,
  },
  uploadbox: {
    height: 130,
    backgroundColor: 'rgba(183, 183, 183, 0.36)',
    lineHeight: 32,
    color: '#5A5A5A',
    borderRadius: 5,
    marginBottom: 14,
    fontWeight: '500',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  uploadbox_bg: {
    height: 130,
    backgroundColor: '#EAEAEA',
    lineHeight: 130,
    color: '#5A5A5A',
    textAlign: 'center',
    borderRadius: 5,
    marginBottom: 14,
    fontWeight: '500',
    padding: 10,
  },
  border_dotted: {
    height: 110,
    borderColor: '#B7B7B7',
    borderWidth: 2,
    borderRadius: 5,
    borderStyle: 'dashed',
    color: '#B7B7B7',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  upload_img: {
    width: 32,
    height: 32,
    marginBottom: 0,
  },
  uploadbox_text: {
    width: '100%',
    lineHeight: 32,
    color: '#5A5A5A',
    fontSize: 12,
    fontWeight: '500',
    textAlign: 'center',
  },
  uploadtitlesm: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#5A5A5A',
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 11,
    fontWeight: '700',
  },
  uploadboxsm: {
    height: 42,
    width: 130,
    backgroundColor: 'rgba(183, 183, 183, 0.36)',
    lineHeight: 32,
    color: '#5A5A5A',
    borderRadius: 5,
    fontSize: 12,
    fontWeight: '500',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadboxsm_txt: {
    height: 42,
    width: 130,
    backgroundColor: 'rgba(183, 183, 183, 0.36)',
    lineHeight: 32,
    color: '#5A5A5A',
    borderRadius: 5,
    fontSize: 12,
    fontWeight: '500',
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  upload_icon: {
    width: 12,
    height: 15,
    marginBottom: 0,
  },
  upload_icon_sm: {
    width: 10,
    height: 12,
    marginBottom: -5,
    marginTop: 10,
  },
  confirmpopup: {
    height: 188,
    backgroundColor: '#ffffff',
    lineHeight: 32,
    color: '#5A5A5A',
    borderRadius: 30,
    marginBottom: 14,
    fontWeight: '500',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 20,
    paddingRight: 20,
  },
  Categoriesview: {
    height: 250,
    backgroundColor: '#ffffff',
    lineHeight: 32,
    color: '#5A5A5A',
    borderRadius: 30,
    marginBottom: 14,
    fontWeight: '500',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 20,
    paddingRight: 20,
  },
  Meidapopup: {
    backgroundColor: '#ffffff',
    lineHeight: 32,
    color: '#5A5A5A',
    borderRadius: 30,
    marginBottom: 14,
    fontWeight: '500',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 10,
    paddingRight: 10,
  },

  confirmpopuptxt: {
    fontSize: 14,
    lineHeight: 22,
    color: '#44852F',
    textAlign: 'center',
  },
  confirmpopuptxt_blue: {
    fontSize: 12,
    lineHeight: 22,
    color: '#387BFA',
    textAlign: 'center',
  },
  confirmpopuptxt_black: {
    fontSize: 14,
    lineHeight: 19,
    color: '#000000',
    textAlign: 'center',
  },
  confirmpopup_img: {
    width: 26,
    height: 26,
    marginTop: 8,
    marginBottom: 9,
  },
  confirmpopup_close_img: {
    width: 16,
    height: 16,
    position: 'absolute',
    top: 24,
    right: 19,
  },

  checkboxContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    marginTop: 10,
    marginLeft: 10,
  },
  checkboxnomargin: {
    marginBottom: 0,
  },
  checkbox_box: {
    alignSelf: 'center',
    marginTop: 0,
    width: 10,
    height: 10,
    marginRight: 6,
  },
  checkbox_text: {
    color: 'rgba(90,90,90,0.74)',
    fontSize: 16,
    lineHeight: 20,
    marginLeft: 15,
    marginBottom: 0,
  },

  prog_step: {
    // marginBottom:110
  },
  fourcol: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  fourcolinn: {
    width: 90,
    height: 90,
    padding: 3,
    position: 'relative',
  },
  imageOncol: {
    flex: 1,
    flexDirection: 'column',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    position: 'relative',
  },
  imagefourcol: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    position: 'relative',
  },
  imagefourcolinn: {
    width: 100,
    height: 100,
    margin: 5,
  },

  videoonecolinn: {
    width: deviceWidth - 100,
    height: 300,
    marginBottom: 20,
  },
  videofourcolinn: {
    width: 100,
    height: 100,
    margin: 2,
  },
  selectedvideo: {
    borderWidth: 2,
    borderRadius: 5,
    width: deviceWidth - 100,
    height: 300,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#44852f',
  },
  selectedimage: {
    borderWidth: 2,
    borderRadius: 5,
    width: 100,
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#44852f',
  },
  buttonmodaltop: {
    position: 'absolute',
    top: 0,
  },
  buttonmodalbottom: {
    top: 60,
  },
  notselectedimage: {
    width: 100,
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#ff0000',
  },

  notselectedvideo: {
    width: deviceWidth - 100,
    height: 300,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#ff0000',
  },
  list_img: {
    width: 80,
    height: 80,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    borderColor: '#44852f',
    borderWidth: 1,
    borderRadius: 5,
  },

  list_video: {
    width: 80,
    height: 70,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    borderColor: '#44852f',
    borderWidth: 1,
    borderRadius: 5,
  },

  list_videos: {
    width: deviceWidth - 100,
    height: 270,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    borderColor: '#44852f',
    borderWidth: 1,
    borderRadius: 5,
  },
  pro_cardcomponent: {
    // display: "flex",
    // flexDirection: 'column',
    // alignItems: 'flex-start',
    // justifyContent: 'center',
    overflow: 'visible',
    borderColor: 'rgba(0,0,0,0.16)',
    borderWidth: 1,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    //height:310,
    marginBottom: 16,
    shadowColor: '#000000',
    shadowOffset: {
      width: 3,
      height: 1,
    },
    shadowOpacity: 0.16,
  },
  pro_detailcardimg: {
    width: '100%',
    height: 167,
    borderRadius: 0,
    margin: 0,
    marginBottom: 14,
    padding: 0,
  },
  pro_cardimg: {
    width: '100%',
    borderRadius: 20,
    margin: 0,
    marginBottom: 14,
    padding: 0,
  },
  pro_cardimg_inn: {
    width: '100%',
    borderRadius: 20,
  },
  pro_detailcardimg_inn: {
    width: '100%',
    borderRadius: 0,
    flex: 1,
  },
  pro_cardimg_Slide: {
    borderRadius: 20,
  },
  pro_card_content: {},
  pro_card_content_detail: {
    marginTop: 40,
  },
  pro_title: {
    color: '#44852F',
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '600',
    marginBottom: 4,
  },
  pro_location: {
    color: '#969CA2',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '400',
    marginBottom: 4,
  },

  icon_pin: {
    width: 8,
    height: 12,
    marginRight: 6,
  },
  icon_txt: {
    color: '#969CA2',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '400',
    marginBottom: 4,
    paddingLeft: 0,
  },
  pro_price: {
    color: '#44852F',
    fontSize: 17,
    lineHeight: 18,
    fontWeight: '500',
    marginBottom: 0,
  },
  price_line: {
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
    color: '#969CA2',
    fontSize: 17,
    lineHeight: 18,
    fontWeight: '500',
    marginBottom: 0,
    marginRight: 10,
  },
  pro_star_icon: {
    width: 65,
    marginTop: 3,
    marginBottom: 25,
  },
  pro_text_right: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    textAlign: 'Right',
  },

  pro_off: {
    backgroundColor: '#44852F',
    width: 73,
    height: 24,
    borderRadius: 5,
    fontSize: 12,
    lineHeight: 24,
    color: '#ffffff',
    textAlign: 'center',
  },
  titleStyle: {
    padding: 16,
    fontSize: 20,
    color: 'white',
    backgroundColor: 'green',
  },
  imageContainerStyle: {
    flex: 1,
    flexDirection: 'column',
    margin: 1,
  },
  imageStyle: {
    height: 120,
    width: '100%',
  },
  fullImageStyle: {
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '98%',
    resizeMode: 'contain',
  },
  cardfullpromotion: {
    /* position: 'absolute', */
    flex: 0.1,
    /* left: 0,
		right: 0,*/
    bottom: 15,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    height: 40,
    alignItems: 'flex-start',
    textAlign: 'center',
  },
  promotionButtons: {
    alignItems: 'center',
    borderRadius: 5,
    width: 50,
    borderWidth: 1,
    lineHeight: 35,
    borderColor: '#44852F',
    justifyContent: 'center',
    flex: 1,
    margin: 5,
    color: '#595B71',
  },
  promotion_text: {
    fontWeight: 'normal',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#44852F',
    height: 35,
    fontSize: 14,
    lineHeight: 25,
    flex: 1,
  },
  promotion_img: {
    width: 20,
    height: 20,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginBottom: 0,
    flex: 1,
  },
  starchildView: {
    justifyContent: 'center',
    flexDirection: 'row',
  },
  centeralignbtn: {
    justifyContent: 'center',
    textAlign: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  star_icon: {
    width: 20,
    width: 20,
    marginTop: 3,
    resizeMode: 'cover',
    marginBottom: 25,
  },
  review_star_icon: {
    width: 15,
    width: 15,
    marginTop: 3,
    resizeMode: 'cover',
    marginBottom: 25,
  },
  reviewmodalView: {
    margin: 20,
    width: deviceWidth / 1.15,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000000',

    height: 300,
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  reviewtextareainput: {
    borderWidth: 1,
    width: deviceWidth / 1.35,
    borderColor: '#B7B7B7',
    borderRadius: 5,
    paddingTop: 0,
    paddingBottom: 12,
    paddingLeft: 12,
    paddingRight: 11,
    overflow: 'hidden',
    color: '#242729',
    fontSize: 16,
    lineHeight: 14,
    fontWeight: '500',
    textAlignVertical: 'top',
    height: 137,
    marginBottom: 2,
    // marginBottom: -1,
  },

  pro_detailcardcomponent: {
    overflow: 'visible',
    borderColor: 'rgba(0,0,0,0.16)',
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    marginBottom: 19,
    paddingTop: 18,
    paddingBottom: 18,
    paddingRight: 10,
    paddingLeft: 10,
    shadowColor: '#000000',
    shadowOffset: {
      width: 3,
      height: 1,
    },
    shadowOpacity: 0.16,
  },
  option_group: {
    backgroundColor: '#EEEFEC',
    height: 49,
    borderRadius: 5,
    display: 'flex',
    flexDirection: 'row',
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginBottom: 14,
    
  },
  option_item_text_gray: {
    color: '#666666',
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '400',
    textAlignVertical: 'top',
    width: 145,
    overflow: 'hidden',
  },
  option_item_radio: {
    color: '#666666',
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '400',
    textAlignVertical: 'top',
    width: 20,
  },
  option_item_text_strike: {
    color: '#969CA2',
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '500',
    textAlignVertical: 'top',
    width: 45,
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
  },
  option_item_text_green: {
    color: '#44852F',
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '500',
    textAlignVertical: 'top',
    width: 45,
  },
  option_item_text_detail_green: {
    color: '#44852F',
    fontSize: 16,
    fontWeight: '500',
    textAlignVertical: 'top',
  },
  option_view_text: {
    color: '#44852F',
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '700',
    textAlignVertical: 'top',
    textAlign: 'center',
    marginTop: 4,
  },
  br_10: {
    borderRadius: 10,
  },
  review_rate_box: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 19,
  },
  reviewmaintitle: {
    color: '#747474',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  review_star: {
    width: 65,
    textAlignVertical: 'center',
  },
  review_rating_txt: {
    color: '#44852F',
    fontSize: 10,
    lineHeight: 16,
    fontWeight: '400',
    marginLeft: 10,
  },
  option_group_btn: {
    backgroundColor: '#ffffff',
    height: 49,
    borderRadius: 5,
    display: 'flex',
    flexDirection: 'row',
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginBottom: 14,
  },
  option_btn: {
    backgroundColor: '#EEEFEC',
    paddingTop: 8,
    paddingBottom: 8,
    paddingRight: 10,
    paddingLeft: 10,
  },
  option_btn_txt: {
    color: '#44852F',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '400',
  },
  sliderImgView: {
    width: deviceWidth,
  },
  option_btn_img: {
    width: 14,
    height: 14,
    margin: 0,
    marginRight: 10,
    padding: 0,
    marginRight: 15,
  },

  contactcomponent: {},

  login_heading: {
    color: '#000000',
    fontSize: 20,
    lineHeight: 27,
    fontWeight: '600',
    marginBottom: 10,
  },
  login_text: {
    color: '#8B959A',
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '400',
    marginBottom: 40,
  },
  input_text_login: {
    paddingLeft: 50,
    marginTop: 0,
    height: 42,
    fontSize: 16,
    lineHeight: 12,
    borderWidth: 1,
    borderColor: '#B7B7B7',
    borderRadius: 5,
    marginBottom: 0,
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: '#B7B7B7',
    color: '#242729',
  },
  viewer_img_close: {
    width: 20,
    height: 20,
    opacity: 1,
    zIndex: 1,
  },
  input_img_login: {
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    position: 'absolute',
    top: 10,
    left: 18,
    zIndex: 1,
  },
  small_text_login: {
    color: '#5A5A5A',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '400',
    marginBottom: 0,
    position: 'absolute',
    top: -9,
    left: 10,
    backgroundColor: '#ffffff',
    zIndex: 1,
  },
  login_txt_btn: {
    color: '#ffffff',
    fontSize: 20,
    lineHeight: 50,
    fontWeight: '600',
    textAlign: 'center',
    width: '100%',
    borderRadius: 10,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 30,
    backgroundColor: '#44852F',
  },

  setting_bg: {
    backgroundColor: '#EEEFEC',
  },
  icon_setting: {
    height: 85,
    width: 85,
    marginBottom: 12,
  },
  setting_top: {
    display: 'flex',
    textAlign: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  setting_title: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    marginBottom: 11,
    color: '#000000',
  },
  setting_num: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '400',
    marginBottom: 11,
    color: '#5D5D5D',
  },
  setting_list: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingRight: 26,
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 19,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.16,
    shadowRadius: 6,
    elevation: 3,
    borderRadius: 15,
    marginBottom: 17,
  },
  setting_list_title: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '400',
    marginBottom: 0,
    color: '#5D5D5D',
    width: '70%',
  },
  setting_list_edit: {
    width: 40,
    height: 17,
    borderRadius: 5,
    backgroundColor: '#AAE697',
    fontSize: 8,
    lineHeight: 17,
    fontWeight: '400',
    marginBottom: 0,
    color: '#44852F',
    textTransform: 'uppercase',
    display: 'flex',
    flexDirection: 'column',
    textAlign: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },

  setting_icon_home: {
    height: 18,
    width: 15,
    marginBottom: 0,
    marginRight: 16,
    marginTop: 2,
  },
  setting_icon_num: {
    height: 12,
    width: 18,
    marginBottom: 0,
    marginRight: 15,
    marginTop: 5,
  },
  setting_icon_env: {
    height: 12,
    width: 16,
    marginBottom: 0,
    marginRight: 16,
    marginTop: 5,
  },
  setting_list_icon: {
    height: 14,
    width: 14,
    marginBottom: 0,
    marginRight: 17,
    marginTop: 2,
  },
  errorMessage: {
    fontSize: 20,
    color: 'red',
    marginLeft: -80,
  },

  logoutBtn: {
    width: '100%',
    borderRadius: 10,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 0,
    backgroundColor: '#228B22',
  },
  logouttext: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
};
